# Generated by Django 3.0.4 on 2020-03-27 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('air_Date', models.CharField(max_length=200)),
                ('ep_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loc_type', models.CharField(max_length=200)),
                ('dimension', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AL', 'Alive'), ('DE', 'Dead'), ('UN', 'Unknown')], default='AL', max_length=2)),
                ('species', models.CharField(max_length=200)),
                ('char_type', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('FE', 'Female'), ('MA', 'Male'), ('GE', 'Genderless'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('image', models.URLField()),
                ('episodes', models.ManyToManyField(to='rickmorty.Episode')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='rickmorty.Location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='rickmorty.Location')),
            ],
        ),
    ]
