# Generated by Django 3.0.4 on 2020-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickmorty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='air_Date',
            new_name='air_date',
        ),
        migrations.AddField(
            model_name='character',
            name='url',
            field=models.CharField(default='google.cl', max_length=200),
        ),
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.CharField(default='google.cl', max_length=200),
        ),
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.CharField(default='google.cl', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('FE', 'Female'), ('MA', 'Male'), ('GE', 'Genderless'), ('UN', 'Unknown')], default='UN', max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('AL', 'Alive'), ('DE', 'Dead'), ('UN', 'Unknown')], default='AL', max_length=200),
        ),
    ]
