# Generated by Django 3.0.4 on 2020-03-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rickmorty', '0002_auto_20200328_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='url',
            new_name='pi_url',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='url',
            new_name='api_url',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='url',
            new_name='api_url',
        ),
    ]
