# Generated by Django 3.0.4 on 2020-03-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickmorty', '0003_auto_20200328_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='api_id',
            field=models.CharField(default=999, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='api_id',
            field=models.CharField(default=998, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='api_id',
            field=models.CharField(default=997, max_length=200),
            preserve_default=False,
        ),
    ]
