# Generated by Django 3.0.4 on 2020-03-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickmorty', '0005_episode_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='residents',
            field=models.CharField(default='tieee', max_length=200),
            preserve_default=False,
        ),
    ]
