# Generated by Django 3.0.4 on 2020-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rickmorty', '0006_location_residents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='episodes',
        ),
        migrations.AddField(
            model_name='character',
            name='episodes',
            field=models.CharField(default='12', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.CharField(max_length=200),
        ),
    ]
