# Generated by Django 3.0.4 on 2020-03-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rickmorty', '0007_auto_20200328_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='pi_url',
            new_name='api_url',
        ),
    ]
